using System.Collections.Generic;
using static Abyss.Rules.TabletopRules;

namespace Abyss.Presentation;
internal sealed class Localization
{
    private readonly MenuState menuState;
    internal Localization(MenuState menuState)
    {
        this.menuState = menuState;
    }

    internal bool English => menuState.English;
    internal string Translate(string portuguese, string english) => menuState.English ? english : portuguese;
    internal string ClassName(int i) => menuState.English ? UiTheme.EnglishNames[i] : UiTheme.Names[i];
    internal string SkillName(int i) => menuState.English ? UiTheme.EnglishSkills[i] : UiTheme.Skills[i];
    internal string EnemyName(char glyph) => EnemyText.Name(glyph, 1, English).ToUpperInvariant();
    internal string EnemyName(Enemy? enemy) => enemy == null ? Translate("SEM ALVO", "NO TARGET") : EnemyText.Name(enemy.Glyph, enemy.Depth, English).ToUpperInvariant();
    internal string HelpText(int topic) => topic switch
    {
        9 => Translate("# GUARDIAO DAS RUINAS\nSeu impacto sismico estilhaca o chao ao redor.\nAfaste-se quando as pedras comecarem a tremer.\n\n# GUARDIAO DAS MARES\nUma onda varre a sala, rouba folego e apaga chamas.\nSaia para os lados do caminho da inundacao.\n\n# SOBERANO DOS ESPOROS\nUma nuvem venenosa cresce onde voce estava.\nAbandone esse lugar antes de os esporos se abrirem.\n\n# GUARDIAO DA FORJA\nUma cruz de fogo deixa brasas pelo caminho.\nEvite as marcas [!] e as chamas que permanecerem.", "# RUIN WARDEN\nIts seismic impact shatters the ground around it.\nStep away when the stones begin to tremble.\n\n# TIDE WARDEN\nA wave sweeps the room, saps breath and puts out flames.\nStep to the sides of the approaching flood.\n\n# SPORE SOVEREIGN\nA poisonous cloud grows where you were standing.\nLeave that spot before the spores burst open.\n\n# FORGE WARDEN\nA cross of fire leaves embers in its wake.\nAvoid the [!] marks and the flames left behind."),
        8 => Translate("# ADVERSARIOS DE ELITE\nRaros campeoes carregam titulos de cores vivas.\nResistem e golpeiam melhor que os demais.\nAlguns guardam equipamentos raros ou reliquias superiores.\n\n# TERRAS ALTERADAS\nTrevas profundas sufocam ate a luz das tochas.\nUma infestacao reune criaturas de uma unica especie.\nVentos quentes sustentam as chamas por mais tempo.\nO ar rarefeito dificulta recuperar o folego.\nTesouros ocultos recompensam quem explora com cuidado.\n\n# PRUDENCIA\nLeia os sinais ao entrar em cada andar.\nOs refugios do mercador permanecem livres destas ameacas.", "# ELITE ADVERSARIES\nRare champions bear vividly colored titles.\nThey endure and strike harder than their kin.\nSome carry rare equipment or greater relics.\n\n# ALTERED LANDS\nDeep darkness smothers even the light of torches.\nAn infestation gathers creatures of a single kind.\nHot drafts keep flames burning longer.\nThin air makes it harder to regain your breath.\nHidden caches reward careful explorers.\n\n# CAUTION\nRead the signs when entering each floor.\nMerchant refuges remain free of these threats."),
        7 => Translate("# LUZ NAS PROFUNDEZAS\nUma tocha acesa afasta a escuridao. Leve reservas.\nDerrube as tochas fixas e recolha-as no chao.\nBaus e o mercador tambem oferecem novas tochas.\n\n# OLEO E FOGO\nBarris tombados espalham oleo. Uma chama pode incendeia-lo.\nArremesse uma tocha pela mochila e mantenha distancia.\nAs chamas ferem aliados e inimigos; a agua as apaga.\n\n# ARMADILHAS\n^ Espinhos nas ruinas; Z descargas nas cisternas.\n% Esporos venenosos nas grutas; V fogo nas forjas.\n\n# TERRAS ESQUECIDAS\nRuinas, cisternas, grutas e forjas guardam a descida.", "# LIGHT IN THE DEPTHS\nA lit torch keeps darkness at bay. Carry spares.\nKnock down fixed torches and collect them from the floor.\nChests and the merchant also offer fresh torches.\n\n# OIL AND FIRE\nFallen barrels spill oil. A flame can set it ablaze.\nThrow a torch from your pack and keep your distance.\nFlames hurt friend and foe; water puts them out.\n\n# TRAPS\n^ Ruin spikes; Z cistern discharges.\n% Cave spores; V forge flame jets.\n\n# FORGOTTEN LANDS\nRuins, cisterns, caves and forges await below."),
        0 => Translate("# O ABISMO\nSob as ruinas, escadas levam a saloes esquecidos.\nA luz da superficie desaparece muito antes do fim da jornada.\n\n# A DESCIDA\nProcure as passagens entre as salas e guarde suas provisoes.\nNem toda sombra precisa ser enfrentada.\nAs escadas sao o caminho para as profundezas.\n\n# O QUE RESTA\nOuro, cicatrizes e lembrancas acompanham quem sobrevive.\nA verdadeira conquista e voltar a encontrar o proximo caminho.", "# THE ABYSS\nBeneath the ruins, stairs lead to forgotten halls.\nDaylight vanishes long before the journey is over.\n\n# THE DESCENT\nSeek passages between chambers and preserve your supplies.\nNot every shadow must be confronted.\nStairs lead farther into the depths.\n\n# WHAT REMAINS\nGold, scars and memories follow those who survive.\nThe true achievement is finding the next path."),
        1 => Translate("# SALAS E CORREDORES\nSalas abertas oferecem espaco, mas tambem deixam voce exposto.\nPassagens estreitas ajudam a separar os perseguidores.\nParedes e esquinas podem esconder sua fuga.\n\n# ESCADAS VIGIADAS\nAlgumas escadas pertencem aos Guardioes.\nEles aguardam na propria sala e nao abandonam seu posto.\nEntrar em seu dominio rompe o silencio.\n\n# UM REFUGIO RARO\nA luz do mercador anuncia uma tregua.\nAli nao ha criaturas a espreita: apenas negocios e outra escada.", "# CHAMBERS AND CORRIDORS\nOpen rooms offer space, but leave you exposed.\nNarrow passages help separate pursuers.\nWalls and corners may conceal your retreat.\n\n# GUARDED STAIRS\nSome stairways belong to the Wardens.\nThey wait in their chamber and never abandon their post.\nEntering their domain breaks the silence.\n\n# A RARE REFUGE\nThe merchant's light promises a truce.\nNo creatures lurk there: only trade and another stairway."),
        2 => Translate("# RUINAS\ns Esqueleto; g Goblin; v Revenante.\nOs mortos dividem os saloes com saqueadores atentos.\n\n# CISTERNAS\nr Rato; d Afogado; l Sanguessuga gigante.\nDentes e garras emergem das aguas esquecidas.\n\n# GRUTAS FUNGICAS\nf Esporito; j Rastejante; m Miconide.\nA vida floresce onde a luz nunca chega.\n\n# FORJAS DAS BRASAS\nh Cao das cinzas; i Diabrete das brasas; k Sentinela de ferro.\nFeras e maquinas vigiam as fornalhas abandonadas.", "# RUINS\ns Skeleton; g Goblin; v Revenant.\nThe dead share these halls with watchful scavengers.\n\n# CISTERNS\nr Rat; d Drowned; l Giant leech.\nTeeth and claws rise from forgotten waters.\n\n# FUNGAL CAVES\nf Sporeling; j Cave crawler; m Myconid.\nLife flourishes where daylight never reaches.\n\n# EMBER FORGES\nh Cinder hound; i Ember imp; k Forged sentinel.\nBeasts and machines watch over abandoned furnaces."),
        3 => Translate("# GUERREIRO\nEnfrenta o perigo de perto, com espada ou adaga.\nArmaduras de placas combinam com sua vocacao.\n\n# MAGO\nConduz a forca arcana por meio de um cajado.\nMantos protegem quem trilha esse caminho.\n\n# ARQUEIRO\nMantem a distancia e confia na precisao do arco.\n\n# LADINO\nEspadas e adagas acompanham seus passos discretos.\nA astucia pode valer tanto quanto a forca.", "# WARRIOR\nFaces danger up close, with sword or dagger.\nPlate armor suits this calling.\n\n# MAGE\nChannels arcane force through a staff.\nRobes shelter those who walk this path.\n\n# ARCHER\nKeeps a distance and trusts the bow's precision.\n\n# ROGUE\nSwords and daggers accompany quiet footsteps.\nCunning can be as valuable as strength."),
        4 => Translate("# ARMAS, VESTES E AMULETOS\nUma boa lamina, um manto ou um talisma podem mudar sua jornada.\nAlgumas pecas exigem experiencia; outras, uma vocacao especifica.\n\n# TESOUROS\nBaus esquecidos guardam equipamentos e provisoes.\nNem tudo o que encontrar servira ao seu caminho.\nO mercador pode dar destino ao que voce nao precisa.\n\n# RELIQUIAS\nPecas comuns e raras dividem espaco com achados extraordinarios.\nArtefatos epicos e lendarios carregam propriedades especiais.\nExamine cada um: poder e utilidade nem sempre sao a mesma coisa.", "# WEAPONS, GARMENTS AND CHARMS\nA good blade, robe or talisman can change your journey.\nSome pieces demand experience; others, a particular calling.\n\n# TREASURES\nForgotten chests hold equipment and supplies.\nNot everything you find will suit your path.\nThe merchant may find a use for what you do not need.\n\n# RELICS\nCommon and rare pieces mingle with extraordinary discoveries.\nEpic and legendary artifacts carry special properties.\nExamine each: power and usefulness are not always the same."),
        5 => Translate("# FRASCOS DE VIDA\nPocoes fecham feridas e devolvem folego aos viajantes.\nGuarde-as com cuidado; a proxima pode estar longe.\n\n# ESSENCIAS DE ENERGIA\nOutros frascos restauram as forcas gastas na jornada.\nCristais encontrados pelo caminho tambem oferecem alivio.\n\n# MOEDAS\nO ouro pesa pouco diante de uma necessidade urgente.\nUm bolso abastecido pode garantir provisoes no proximo refugio.\n\n# PRUDENCIA\nEscolha quando lutar e quando recuar.\nNenhum tesouro vale muito para quem nao sobrevive para usa-lo.", "# HEALTH DRAUGHTS\nPotions close wounds and restore a traveler's breath.\nGuard them carefully; the next may be far away.\n\n# ENERGY ESSENCES\nOther bottles replenish strength spent on the journey.\nCrystals found along the way also offer relief.\n\n# COINS\nGold weighs little against an urgent need.\nA full purse may secure supplies at the next refuge.\n\n# PRUDENCE\nChoose when to fight and when to retreat.\nTreasure means little to those who cannot survive to use it."),
        _ => Translate("# O MERCADOR\nUm viajante de capuz mantem seu pequeno refugio entre as ruinas.\nNinguem sabe como suas mercadorias chegam tao fundo.\n\n# SUA BANCA\nHa armas, vestes, amuletos e frascos entre seus pertences.\nSua oferta varia: examine as pecas antes de se decidir.\nEle tambem compra equipamentos e provisoes dos aventureiros.\n\n# PALAVRAS NA PENUMBRA\n\"O Abismo cobra caro. Eu aceito moedas.\"\n\"Volte vivo. Bons clientes sao raros.\"\n\n# TREGUA\nA sala do mercador e um lugar seguro antes de continuar a descida.", "# THE MERCHANT\nA hooded traveler keeps a small refuge among the ruins.\nNobody knows how his wares reach these depths.\n\n# HIS STALL\nWeapons, garments, charms and bottles fill his belongings.\nHis wares vary: examine each piece before deciding.\nHe also buys equipment and supplies from adventurers.\n\n# WORDS IN THE GLOOM\n\"The Abyss asks a price. I take coins.\"\n\"Come back alive. Good customers are rare.\"\n\n# TRUCE\nThe merchant's room is a safe place before continuing downward.")};
    internal static string MonsterName(char glyph, bool english) => EnemyText.Name(glyph, 1, english);
    internal string StatsLine(Attributes a, bool first) => first ? Translate($"FOR {a.Strength}  DES {a.Dexterity}", $"STR {a.Strength}  DEX {a.Dexterity}") : Translate($"CON {a.Constitution}  INT {a.Intelligence}", $"CON {a.Constitution}  INT {a.Intelligence}");
    internal string OfferName(Offer offer) => offer.Gear is Gear g ? GearLabel(g) : offer.Potion == 0 ? Translate("Pocao de vida", "Health potion") : offer.Potion == 1 ? Translate("Pocao de energia", "Energy potion") : Translate("Tocha", "Torch");
    internal string MerchantSpeech() => Translate(new[] { "O Abismo cobra caro. Eu aceito moedas.", "Aco firme, frascos cheios. Escolha bem.", "Aqui, ate as sombras respeitam a tregua.", "Volte vivo. Bons clientes sao raros." }[menuState.MerchantQuote], new[] { "The Abyss asks a price. I take coins.", "Steady steel, full bottles. Choose well.", "Here, even shadows honor the truce.", "Come back alive. Good customers are rare." }[menuState.MerchantQuote]);
    internal string GearStats(Gear gear)
    {
        if (gear.Slot == GearSlot.Weapon)
            return Translate($"Dano: {new DamageDice(1, gear.Sides, gear.Power)} + ", $"Damage: {new DamageDice(1, gear.Sides, gear.Power)} + ") + (gear.Kind == GearKind.Sword ? Translate("FOR", "STR") : gear.Kind == GearKind.Staff ? "INT" : Translate("DES", "DEX"));
        var b = gear.AttributeBonus;
        var parts = new List<string>();
        if (gear.Slot == GearSlot.Armor)
            parts.Add($"{Translate("CA", "AC")} {gear.ArmorClass}");
        if (b.Strength != 0)
            parts.Add(Translate($"FOR +{b.Strength}", $"STR +{b.Strength}"));
        if (b.Dexterity != 0)
            parts.Add(Translate($"DES +{b.Dexterity}", $"DEX +{b.Dexterity}"));
        if (b.Constitution != 0)
            parts.Add($"CON +{b.Constitution}");
        if (b.Intelligence != 0)
            parts.Add($"INT +{b.Intelligence}");
        return string.Join(" | ", parts);
    }

    internal string GearName(Gear g) => Translate(new[] { "Espada", "Adaga", "Cajado", "Arco", "Placas", "Couro", "Manto", "Amuleto" }[(int)g.Kind], new[] { "Sword", "Dagger", "Staff", "Bow", "Plate", "Leather", "Robe", "Amulet" }[(int)g.Kind]);
    internal string RarityName(Rarity r) => Translate(new[] { "Comum", "Raro", "Epico", "Lendario" }[(int)r], new[] { "Common", "Rare", "Epic", "Legendary" }[(int)r]);
    internal string GearLabel(Gear g) => $"{GearName(g)} / {RarityName(g.Quality)}" + (g.Grade > 0 ? $" +{g.Grade}" : "");
    internal string SlotName(int slot) => Translate(new[] { "ARMA", "ARMADURA", "ACESSORIO" }[slot], new[] { "WEAPON", "ARMOR", "ACCESSORY" }[slot]);
    internal string GearNameFor(Gear gear, bool en)
    {
        bool previous = menuState.English;
        menuState.English = en;
        string name = GearLabel(gear);
        menuState.English = previous;
        return name;
    }

    internal string GearEffect(Gear g) => g.Quality < Rarity.Epic ? Translate("Sem efeito especial.", "No special effect.") : g.Slot switch
    {
        GearSlot.Weapon => g.Quality == Rarity.Epic ? Translate("Impacto: +1d4 de dano ao acertar.", "Impact: +1d4 damage on hit.") : Translate("Impacto: +1d6; drena ate 2 PV ao acertar.", "Impact: +1d6; drains up to 2 HP on hit."),
        GearSlot.Armor => Translate($"Protecao: reduz dano recebido em {(g.Quality == Rarity.Epic ? 1 : 2)}.", $"Protection: reduces incoming damage by {(g.Quality == Rarity.Epic ? 1 : 2)}."),
        _ => Translate($"Foco: +{(g.Quality == Rarity.Epic ? 1 : 2)} energia por abate.", $"Focus: +{(g.Quality == Rarity.Epic ? 1 : 2)} energy per kill.")};
}
